# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocomapapp', '0002_auto_20161126_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='cocomapapp.Tag'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='cocomapapp.Tag'),
        ),
    ]
