# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocomapapp', '0004_auto_20161203_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='negative_reaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relation',
            name='positive_reaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
