# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocomapapp', '0005_auto_20161203_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
