# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocomapapp', '0006_tag_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
