# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 10:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocomapapp', '0007_auto_20161207_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='hidden',
        ),
        migrations.AddField(
            model_name='tag',
            name='hidden_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), blank=True, null=True, size=None),
        ),
    ]
