# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocomapapp', '0009_auto_20161115_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='negative_reaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='positive_reaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cocomapapp.Topic'),
        ),
    ]
