# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocomapapp', '0013_auto_20161117_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='topic_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocomapapp.Topic'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='topic_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relates_to', to='cocomapapp.Topic'),
        ),
    ]
