# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocomapapp', '0016_auto_20161117_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='cocomapapp.Tag'),
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='cocomapapp.Tag'),
        ),
    ]
